name: flutter_maps
description: App Flutter + OSM + Supabase para reportar zonas peligrosas
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Mapas (OpenStreetMap via flutter_map)
  flutter_map: ^8.2.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.0

  # Estado
  flutter_riverpod: ^2.5.1

  # Supabase
  supabase_flutter: ^2.3.4

  # Ubicación + cámara/galería
  geolocator: ^12.0.0
  image_picker: ^1.1.2

  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    # Para cargar variables en runtime
    - .env
